ignoreGeneratedHeader = false
severity = "error"
confidence = 0.8
errorCode = 1
warningCode = 0

[rule.file-header]
    arguments = ["MIT License.*"]
[rule.blank-imports]
[rule.imports-blacklist]
    arguments = ["unsafe"]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.empty-block]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.superfluous-else]
[rule.time-naming]
[rule.unexported-return]
[rule.unreachable-code]
[rule.unused-parameter]
[rule.var-declaration]
[rule.var-naming]
[rule.argument-limit]
    arguments = [5]
[rule.atomic]
[rule.bare-return]
[rule.bool-literal-in-expr]
[rule.call-to-gc]
[rule.confusing-results]
[rule.constant-logical-expr]
[rule.cyclomatic]
    arguments = [15]
[rule.deep-exit]
[rule.duplicated-imports]
[rule.flag-parameter]
    Disabled = true
[rule.function-result-limit]
    arguments = [4]
[rule.import-shadowing]
[rule.line-length-limit]
    arguments = [120]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.range-val-in-closure]
[rule.struct-tag]
[rule.unhandled-error]
[rule.unnecessary-stmt]
[rule.unused-receiver]
[rule.waitgroup-by-value]
